spring.application.name=capcay_v3-demo7
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
# reCAPTCHA Configuration
recaptcha.site-key=YOUR_SITE_KEY
recaptcha.secret-key=YOUR_SECRET_KEY
recaptcha.enabled=true
